services:
  swen2-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: swen2
      POSTGRES_PASSWORD: swen2
      POSTGRES_DB: search
    volumes:
      - "swen2-data:/var/lib/postgresql/data"

volumes:
  swen2-data:
